@ScriptsPorTabela/H_ANTIVIRAIS_COVID.sql
@ScriptsPorTabela/H_ANTIVIRAIS_GRIPE.sql
@ScriptsPorTabela/H_ASPECTOS_TOMOGRAFIA.sql
@ScriptsPorTabela/H_CASOS.sql
@ScriptsPorTabela/H_CASOS_AMOSTRAS.sql
@ScriptsPorTabela/H_CASOS_ANTIVIRAIS_COVID.sql
@ScriptsPorTabela/H_CASOS_ANTIVIRAIS_GRIPE.sql
@ScriptsPorTabela/H_CASOS_COMORBIDADES.sql
@ScriptsPorTabela/H_CASOS_EVOLUCOES.sql
@ScriptsPorTabela/H_CASOS_RAIOSX.sql
@ScriptsPorTabela/H_CASOS_SINTOMAS.sql
@ScriptsPorTabela/H_CASOS_TOMOGRAFIA.sql
@ScriptsPorTabela/H_CLASSIFICACOES.sql
@ScriptsPorTabela/H_COMORBIDADES.sql
@ScriptsPorTabela/H_CRITERIOS_ENCERRAMENTO.sql
@ScriptsPorTabela/H_DOSES.sql
@ScriptsPorTabela/H_ENCERRAMENTOS.sql
@ScriptsPorTabela/H_ESCOLARIDADES.sql
@ScriptsPorTabela/H_ESTADOS.sql
@ScriptsPorTabela/H_EVOLUCOES.sql
@ScriptsPorTabela/H_FABRICANTES.sql
@ScriptsPorTabela/H_GENERO.sql
@ScriptsPorTabela/H_IDADES_GESTACIONAIS.sql
@ScriptsPorTabela/H_INTERNACOES.sql
@ScriptsPorTabela/H_MUNICIPIOS.sql
@ScriptsPorTabela/H_RACAS.sql
@ScriptsPorTabela/H_RESULTADOS_RAIOX.sql
@ScriptsPorTabela/H_RESULTADOS_TESTE_ANTIGENO.sql
@ScriptsPorTabela/H_RESULTADOS_TESTE_RTPC.sql
@ScriptsPorTabela/H_RESULTADOS_TESTE_SOROLOGICO.sql
@ScriptsPorTabela/H_SINTOMAS.sql
@ScriptsPorTabela/H_SUPORTE_VENTILADOR.sql
@ScriptsPorTabela/H_TESTES_ANTIGENO.sql
@ScriptsPorTabela/H_TESTES_ANTIGENOS_VIRUS.sql
@ScriptsPorTabela/H_TESTES_RTPCR.sql
@ScriptsPorTabela/H_TESTES_RTPCR_VIRUS.sql
@ScriptsPorTabela/H_TESTE_SOROLOGICOS.sql
@ScriptsPorTabela/H_TIPOS_AMOSTRA.sql
@ScriptsPorTabela/H_TIPOS_AMOSTRAS_SOROLOGICAS.sql
@ScriptsPorTabela/H_TIPOS_TESTES_SOROLOGICOS.sql
@ScriptsPorTabela/H_TIPOS_TESTE_ANTIGENO.sql
@ScriptsPorTabela/H_TRABALHA_ANIMAIS.sql
@ScriptsPorTabela/H_UNIDADES.sql
@ScriptsPorTabela/H_UTI.sql
@ScriptsPorTabela/H_VACINAS_COVID.sql
@ScriptsPorTabela/H_VACINAS_GRIPE.sql
@ScriptsPorTabela/H_VIRUS_RESPIRATORIOS.sql
@ScriptsPorTabela/H_ZONAS.sql